### ISSUE TITLE
great work!

### ISSUE THREAD

**Issue by aquynh** [stievie/UnicornPascal#1]
we have linked to UnicornPascal at https://github.com/unicorn-engine/unicorn/blob/master/bindings/README, and also in http://www.unicorn-engine.org/download/

thanks for the great work!

**Comment by stievie** [comment]
Thank you, and thank you for *your* great work (also for Capstone). I just translated some header files, and that wasn't very hard, since you didn't use some weird C feature :-).

**Comment by aquynh** [comment]
yes, we want to keep the code as portable as possible.

it seems there are still some issues with your samples (where you draw a redbox in one screenshot). if you see the same issue with original C code, then that is a bug, perhaps for Windows only. please let me know then.

thanks.

**Comment by stievie** [comment]
I'll throw an eye there ;-). My first thought was, it's most likely a bug in my sample, but to me it seems to be exactly the same as the original C sample.

**Comment by aquynh** [comment]
was this with v0.9, or latest code from Github? if latest code still has this issue on Windows, then that is definitely a bug.

what is your Windows edition?

**Comment by stievie** [comment]
I cloned it from GitHub 7th Nov. 2015: SHA-1: 938d0b89ebc4adf9e1acc1750a3400a2acce0769

**Comment by stievie** [comment]
But for testing on Windows I used the precompiled binaries downloaded from your Homepage. I didn't compile it myself on Windows.

**Comment by aquynh** [comment]
that is considered the latest code, so there is a bug.

what is your Windows version? 32bit or 64bit?

if you can fix this issue, please send us a PR. thanks.

**Comment by stievie** [comment]
I use Windows 7 64 Bit, and the SampleX86 is also a 64 Bit binary, and thus uses the 64 Bit Unicorn binary.

**Comment by aquynh** [comment]
oh then you should recompile to with Github code for the latest Windows binaries, which fixed quite a lot of issues since v0.9.

**Comment by stievie** [comment]
Finally I got it compiling on Windows with MSYS2 (a pleasure to see pacman on Windows :-) and MinGW64, my steps:
1. Install MSYS2
2. Follow https://github.com/unicorn-engine/unicorn/blob/master/COMPILE.TXT
3. Install Python2 `pacman -S python2`
4. cd to Unicorn and compile with:

    export PATH=/mingw64/bin:${PATH}
    export CC=/mingw64/bin/gcc.exe
    python=/bin/python2 ./make.sh

Pulled from GitHub 11.11.2015: SHA-1: e6fe7a8b5494b1aa6ad067932f5ccd101cb00328.

The original sample_x86 (64 Bit) seems to work fine now on Windows, here is the output:

    >  sample_x86.exe -64
    [...]
    ===================================
    Emulate x86_64 code with 'syscall' instruction
    >>> Emulation done. Below is the CPU context
    >>> RAX = 0x200

I'll try it with my samples and write the results here.

**Comment by aquynh** [comment]
i dont remember having to install Python2. without it, you could not compile??

**Comment by stievie** [comment]
No, it wasn't installed with MSYS2.

**Comment by aquynh** [comment]
no, this requires Python2 to run some scripts at compile time. Python3 does not work.

i updated COMPILE.TXT with your name credited: https://github.com/unicorn-engine/unicorn/commit/dcde01daef0391fcffd3e156c9d2e8da6aa48498
